### ISSUE TITLE
Skip Intros Button

### ISSUE THREAD

**Issue by aklinker1** [anime-skip/player#172]
When auto-skipping is enabled, letst shows a button to skip over a section, similar to Netflix or Disney+.

### Requirements

- [ ] **The button should show up when "Auto-skip Sections" is unchecked** (rather than adding a new preference)
  - We'll also need to change the behavior of the "What do you want to watch?" checkboxes - They're disabled when "Auto-skip Sections" is unchecked. With this feature, lets leave them enabled in that case
- [ ] **Show the button in the bottom right of the player**
  - It should be above the toolbar/timeline
  - When the timestamp panel is open, it should move toward the middle so it's not behind the panel on short screens
- [ ] **Only show the button when the toolbar is visible**
  - So it should show up as you move your mouse around, but it should be hidden after the toolbar goes away. Moving the mouse again should bring it back
  - **When entering a skipped section for the first time, show the toolbar so the button is visible**
- [ ] The button should be hidden after leaving a skipped section
- [ ] **It should show for every type of timestamp you've chosen to skip**
- [ ] **When clicked, it should skip until the next timestamp the user wants to watch** (this is the exact same behavior as auto-skip, you can probably call the same function)

### Random Thoughts

I feel like hiding this kind of button after a delay is a bad UX, it might disappear right before someone clicks on it.

A possible solution is to a timer bar or circle that counts down visually, but then what happens after the count-down is done? Does it skip or does it hide the button? I think a count down forces the user to rush to make a decision, which I don't want to do. That's something I don't like about netflix's next episode button and youtube's autoplay.

So that's why I decided to leave it as visible.

**Comment by logiczsniper** [comment]
I got a great start this morning, but now I need to test; how can I test this feature?

**Comment by aklinker1** [comment]
What do you mean, test? Do you need help running the extension? Or finding an episode with timestamps?

**Comment by logiczsniper** [comment]
The latter - I can run the extension with the fake streaming service but that test episode does not have any timestamps, as such I cannot test that the skip button works.

**Comment by aklinker1** [comment]
When you start the player with `pnpm start`, it uses the test server and test databases. So you can just connect the episode on the fake streaming service, and add your own timestamps.

You'll need to sign in to create your account. Depending on when you created your account vs when I last copied the prod database over to the test environment (a long time ago), you may need to create an account. Try your regular sign in credentials for production. If that doesn't work, copy, paste, and fill out this query on the API playground to create an account:

```gql
mutation {
  createAccount(
    username: "<change-me>",
    email: "<change-me>",
    passwordHash: "<md5-hash-of-password>",
    recaptchaResponse: "password1",
  ) {
    authToken
    refreshToken
    account {
      username
      email
    }
  }
}
```

> Leave `recaptchaResponse` alone, and use a tool like https://coding.tools/md5 to generate the `passwordHash` of a password

**Comment by aklinker1** [comment]
Or if you don't want to connect that url, you can go to an existing episode with timestamps:

```gql
# Copy paste into http://test.api.anime-skip.com/graphiql
{
  searchEpisodes(search: "a") {
    urls {
      url
      source
    }
  }
}
```

**Comment by logiczsniper** [comment]
Awesome, it seems my account was old enough :)
Thanks!

**Comment by logiczsniper** [comment]
> When clicked, it should skip until the next timestamp the user wants to watch

What should the button text be? 
I currently am just skipping the current section so the text is `Skip {section}`; but let's say they do not want to watch a recap nor an intro and these are back to back; should it say `Skip Recap and Intro`?

Another question: do you have any preferences for what the button looks like? E.g. raised themed button or flat black (similar to Return to Anime Skip button)

**Comment by aklinker1** [comment]
No, let's keep it simple and just say "Skip Intro" in that case.

As for the button, maybe flat transparent or raised dark? Whichever looks best, probably raised dark since that has a background color

**Comment by logiczsniper** [comment]
OK the functionality of the button is pretty much done, here is what is left: 
- [ ] Style; choose a button style from the two you mentioned
- [ ] Positioning; this seems like it could be tricky to move it if the timestamps or settings dialogs are open
- [ ] Test; I would like to test this a lot more with longer videos / more timestamps would make this easier, so I am thinking of a way to do so. I have a couple ideas but if none of them work i'll be sure to ask ;)

**Comment by aklinker1** [comment]
> - Positioning; this seems like it could be tricky to move it if the timestamps or settings dialogs are open

Yeah, this is the trickiest part of the feature lol.

> - Test; I would like to test this a lot more with longer videos / more timestamps would make this easier, so I am thinking of a way to do so. I have a couple ideas but if none of them work i'll be sure to ask ;) 

Once it's ready, I'll test it out as well for about a week. You'll just run `pnpm build` or `pnpm build:chrome` depending on your daily driver.  This will build it pointing towards the prod API, making it equivalent to what you install from the store.

Then just disable the existing extension, install the one you just built, and use it for a few days as you normally would. Depending on the changes that were required, I might spend a week testing like this. This one should be fairly simple though, shouldn't take more than a day.
