### ISSUE TITLE
When opening extension menu while it appears like this

### ISSUE THREAD

**Issue by LoneWolf993** [anime-skip/player#241]
![Screenshot (59)](https://user-images.githubusercontent.com/66156681/167999032-bebbae5f-491f-422e-8cf3-e9093001327b.png)
![Screenshot (60)](https://user-images.githubusercontent.com/66156681/167999124-23c0c0aa-b882-4c12-ae46-135fdc0fb75d.png)

**Comment by aklinker1** [comment]
Is that edge?

**Comment by aklinker1** [comment]
Popup has been removed from V2 for now, closing this issue.
