### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lordesgar** [anime-skip/player#273]
Not sure if this is where I should be asking this, but can other people change my timestamps? I think that one of my previous timestamps may have been changed by someone else. It would be nice if we could have separate timestamps for different people, so that you could choose whose you want to use.

**Comment by aklinker1** [comment]
Yes, timestamps are shared between everyone, there is one set of timestamps per episode that everyone can edit. This may change in the future, and each user might have their own set of timestamps for each episode.
